// Converts the Figma token exports in foundation/ into CSS custom properties in css/.
// Run from the repo root: npm run build
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'foundation');
const OUT = join(ROOT, 'css');
const PREFIX = 'ds';

const load = (file) => JSON.parse(readFileSync(join(SRC, file), 'utf8'));

// Flattens a DTCG tree into [{ path, value, type, description, codeSyntax }].
function flatten(node, path = []) {
  if (node && typeof node === 'object' && '$value' in node) {
    return [{
      path,
      value: node.$value,
      type: node.$type,
      description: node.$description,
      codeSyntax: node.$extensions?.codeSyntax?.WEB,
    }];
  }
  // Figma keeps scale steps as strings ("050", "100"); JS would list "9999" before "0000".
  const entries = Object.entries(node).filter(([key]) => !key.startsWith('$'));
  if (entries.every(([key]) => /^\d+$/.test(key))) entries.sort(([a], [b]) => Number(a) - Number(b));
  return entries
    .flatMap(([key, child]) => flatten(child, [...path, key]));
}

const varName = (path) => `--${PREFIX}-${path.join('-').toLowerCase()}`;

// Primitives are unitless in Figma; units are added here, once, by group.
function primitiveValue({ path, value, type }) {
  const group = path.slice(1, 3).join('.');
  if (type === 'color') return value;
  if (group === 'font.family') {
    const generic = /mono/i.test(value) ? 'monospace' : /georgia|serif/i.test(value) && !/sans/i.test(value) ? 'serif' : 'sans-serif';
    return value === 'system-ui' ? 'system-ui, sans-serif' : `"${value}", ${generic}`;
  }
  if (group === 'font.weight') return String(value);
  if (group === 'font.tracking') return value === 0 ? '0' : `${value / 100}em`; // Figma letter spacing is a %
  if (path[1] === 'opacity') return String(value / 100);
  if (path[1] === 'duration') return `${value}ms`;
  return `${value}px`; // space, size, radius, border, font.size, font.line-height
}

// Literal (non-alias) numbers in the semantic collections.
function literalValue({ path, value }) {
  if (typeof value === 'string') return value;
  if (path[0] === 'layer' || path.at(-1) === 'columns') return String(value);
  return `${value}px`; // breakpoints, container widths
}

const resolve = (token) => {
  const alias = typeof token.value === 'string' && token.value.match(/^\{(.+)\}$/);
  return alias ? `var(${varName(alias[1].split('.'))})` : literalValue(token);
};

const comment = (text) => (text ? `  /* ${text.replace(/\*\//g, '* /')} */\n` : '');
// Descriptions repeat across the properties of a text style, so each is written once.
const decls = (tokens, value = resolve, describe = true) =>
  tokens.map((t, i) => {
    const note = describe && t.description !== tokens[i - 1]?.description ? comment(t.description) : '';
    return `${note}  ${varName(t.path)}: ${value(t)};`;
  }).join('\n');
const block = (selector, body, indent = '') =>
  `${indent}${selector} {\n${body.split('\n').map((l) => indent + l).join('\n')}\n${indent}}`;
const header = (title, sources) =>
  `/* Lysch Web DS — ${title}\n * Generated by scripts/build-css.mjs from ${sources}. Do not edit by hand. */`;

// Compare by name so modes only re-declare what they change.
const changed = (base, other) => {
  const byName = new Map(base.map((t) => [varName(t.path), t.value]));
  return other.filter((t) => byName.get(varName(t.path)) !== t.value);
};

// CSS names always come from the token path. A Figma codeSyntax that disagrees is
// reported once per group (e.g. per text style), not once per file and property.
const warnings = new Set();
function checkCodeSyntax(tokens) {
  for (const t of tokens) {
    const expected = `var(${varName(t.path)})`;
    if (!t.codeSyntax || t.codeSyntax === expected) continue;
    const group = t.path.slice(0, -1).join('.');
    const got = t.codeSyntax.replace(/^var\(|\)$/g, '').replace(`-${t.path.at(-1).toLowerCase()}`, '');
    warnings.add(`${group}: Figma codeSyntax says ${got}-*, the CSS uses ${varName(t.path.slice(0, -1))}-*`);
  }
}

function loadSet(file) {
  const tokens = flatten(load(file));
  checkCodeSyntax(tokens);
  return tokens;
}

const files = {};

// Primitives
const primitives = flatten(load('Primitives.json'));
files['tokens/primitives.css'] =
  header('primitives', 'Primitives.json') + '\n' +
  block(':root', decls(primitives, primitiveValue, false)) + '\n';

// Theme: light on :root, dark through the OS preference or data-mode.
// Dark re-declares every color, not only the changed ones, so that aliases between
// semantic colors resolve again inside a scoped [data-mode] element.
const light = loadSet('System-Light.json');
const dark = loadSet('System-Dark.json');
const isColor = (t) => t.path[0] === 'color';
const nonColorDiff = changed(light.filter((t) => !isColor(t)), dark.filter((t) => !isColor(t)));
if (nonColorDiff.length) warnings.add(`Dark mode changes non-color tokens, which are ignored: ${nonColorDiff.map((t) => t.path.join('.')).join(', ')}`);
const lightColors = light.filter(isColor);
const darkColors = dark.filter(isColor);
files['tokens/theme.css'] = [
  header('theme (light + dark)', 'System-Light.json / System-Dark.json'),
  block(':root', decls(light.filter((t) => !isColor(t)))),
  block(':root,\n[data-mode="light"]', '  color-scheme: light;\n' + decls(lightColors)),
  '@media (prefers-color-scheme: dark) {\n' +
    block(':root:not([data-mode="light"])', '  color-scheme: dark;\n' + decls(darkColors, resolve, false), '  ') + '\n}',
  block('[data-mode="dark"]', '  color-scheme: dark;\n' + decls(darkColors, resolve, false)),
  '',
].join('\n\n');

// Density: regular by default, switchable on any element.
const density = Object.fromEntries(['Regular', 'Compact', 'Comfortable'].map((m) => [m, loadSet(`Density-${m}.json`)]));
files['tokens/density.css'] = [
  header('density', 'Density-*.json'),
  block(':root,\n[data-density="regular"]', decls(density.Regular)),
  block('[data-density="compact"]', decls(density.Compact, resolve, false)),
  block('[data-density="comfortable"]', decls(density.Comfortable, resolve, false)),
  '',
].join('\n\n');

// Platform: pointer by default, touch on coarse pointers or data-platform="touch".
const web = loadSet('Platform-Web.json');
const touch = loadSet('Platform-Touch.json');
files['tokens/platform.css'] = [
  header('platform', 'Platform-Web.json / Platform-Touch.json'),
  block(':root,\n[data-platform="web"]', decls(web)),
  '@media (pointer: coarse) {\n' + block(':root:not([data-platform="web"])', decls(touch, resolve, false), '  ') + '\n}',
  block('[data-platform="touch"]', decls(touch, resolve, false)),
  '',
].join('\n\n');

// Motion: full by default, reduced with the OS setting or data-motion="reduced".
const full = loadSet('Motion-Full.json');
const reduced = loadSet('Motion-Reduced.json');
files['tokens/motion.css'] = [
  header('motion', 'Motion-Full.json / Motion-Reduced.json'),
  block(':root,\n[data-motion="full"]', decls(full)),
  '@media (prefers-reduced-motion: reduce) {\n' + block(':root:not([data-motion="full"])', decls(reduced, resolve, false), '  ') + '\n}',
  block('[data-motion="reduced"]', decls(reduced, resolve, false)),
  '',
].join('\n\n');

// Viewport: mobile first, each breakpoint re-declares only what changes.
// Breakpoint widths come from layout.breakpoint in the system collection.
const breakpoints = Object.fromEntries(
  light.filter((t) => t.path.join('.').startsWith('layout.breakpoint')).map((t) => [t.path.at(-1), t.value]),
);
const viewports = ['SM', 'MD', 'LG', 'XL'].map((s) => ({ size: s.toLowerCase(), tokens: loadSet(`Viewport-${s}.json`) }));
const viewportBlocks = [block(':root', decls(viewports[0].tokens))];
for (let i = 1; i < viewports.length; i++) {
  const { size, tokens } = viewports[i];
  const diff = changed(viewports[i - 1].tokens, tokens);
  viewportBlocks.push(`/* ${size.toUpperCase()} — ${breakpoints[size]}px and up */\n@media (min-width: ${breakpoints[size]}px) {\n` +
    block(':root', decls(diff, resolve, false), '  ') + '\n}');
}
files['tokens/viewport.css'] = [header('viewport', 'Viewport-*.json'), ...viewportBlocks, ''].join('\n\n');

// Typography classes: one class per text style, built on the type.* tokens.
const styles = [...new Set(
  [...light, ...viewports[0].tokens]
    .filter((t) => t.path[0] === 'type')
    .map((t) => t.path.slice(0, -1).join('-')),
)];
const ORDER = ['display', 'headline', 'title', 'body', 'label', 'code'];
const SIZE_ORDER = ['xlg', 'lg', 'md', 'sm'];
styles.sort((a, b) => {
  const [, ga, sa] = a.split('-');
  const [, gb, sb] = b.split('-');
  return ORDER.indexOf(ga) - ORDER.indexOf(gb) || SIZE_ORDER.indexOf(sa) - SIZE_ORDER.indexOf(sb);
});
const PROPS = ['font-family', 'font-size', 'line-height', 'font-weight', 'letter-spacing'];
files['typography.css'] = [
  header('typography classes', 'the type.* tokens'),
  ...styles.map((s) => block(`.${PREFIX}-${s}`, PROPS.map((p) => `  ${p}: var(--${PREFIX}-${s}-${p});`).join('\n'))),
  '',
].join('\n\n');

// Bundle: everything a site needs in one file.
const parts = ['tokens/primitives.css', 'tokens/theme.css', 'tokens/density.css', 'tokens/platform.css', 'tokens/motion.css', 'tokens/viewport.css', 'typography.css'];
files['lysch-web-ds.css'] = header('bundle', parts.join(', ')) + '\n' + parts.map((p) => files[p]).join('\n');

for (const [path, content] of Object.entries(files)) {
  mkdirSync(dirname(join(OUT, path)), { recursive: true });
  writeFileSync(join(OUT, path), `@charset "UTF-8";\n${content}`);
}

console.log(`Wrote ${Object.keys(files).length} files to css/`);
if (warnings.size) console.warn(`\n${warnings.size} warnings:\n- ${[...warnings].join('\n- ')}`);
